# Databricks notebook source
# MAGIC %sql
# MAGIC -- Select your Unity Catalog
# MAGIC USE CATALOG customer_demo;
# MAGIC
# MAGIC -- Create necessary schemas for medallion architecture
# MAGIC CREATE SCHEMA IF NOT EXISTS CUSTOMER_bronze;
# MAGIC CREATE SCHEMA IF NOT EXISTS CUSTOMER_silver;
# MAGIC CREATE SCHEMA IF NOT EXISTS CUSTOMER_gold;

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS CUSTOMER_bronze.CUSTOMER (
# MAGIC     CUSTOMER_ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
# MAGIC     FIRST_NAME STRING,
# MAGIC     LAST_NAME STRING,
# MAGIC     MIDDLE_NAME STRING,
# MAGIC     GENDER STRING,
# MAGIC     DATE_OF_BIRTH DATE,
# MAGIC     EMAIL STRING,
# MAGIC     PHONE STRING,
# MAGIC     CREATED_DATE DATE,
# MAGIC     LAST_UPDATED_DATE DATE,
# MAGIC     STATUS STRING
# MAGIC );
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS CUSTOMER_bronze.CUSTOMER_ADDRESSES (
# MAGIC     ADDRESS_ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
# MAGIC     CUSTOMER_ID BIGINT REFERENCES CUSTOMER_bronze.CUSTOMER,
# MAGIC     ADDRESS_TYPE STRING,
# MAGIC     ADDRESS_LINE_1 STRING,
# MAGIC     ADDRESS_LINE_2 STRING,
# MAGIC     CITY STRING,
# MAGIC     STATE STRING,
# MAGIC     POSTAL_CODE STRING,
# MAGIC     COUNTRY STRING,
# MAGIC     IS_PRIMARY BOOLEAN
# MAGIC );
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS CUSTOMER_bronze.CUSTOMER_CONTACTS (
# MAGIC     CONTACT_ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
# MAGIC     CUSTOMER_ID BIGINT REFERENCES CUSTOMER_bronze.CUSTOMER,
# MAGIC     CONTACT_TYPE STRING,
# MAGIC     CONTACT_VALUE STRING,
# MAGIC     PREFERRED_CONTACT_METHOD BOOLEAN
# MAGIC );
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS CUSTOMER_bronze.CUSTOMER_PREFERENCES (
# MAGIC     PREFERENCE_ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
# MAGIC     CUSTOMER_ID BIGINT REFERENCES CUSTOMER_bronze.CUSTOMER,
# MAGIC     PREFERENCE_TYPE STRING,
# MAGIC     PREFERENCE_VALUE STRING,
# MAGIC     OPTED_IN BOOLEAN
# MAGIC );
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS CUSTOMER_bronze.CUSTOMER_TRANSACTIONS (
# MAGIC     TRANSACTION_ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
# MAGIC     CUSTOMER_ID BIGINT REFERENCES CUSTOMER_bronze.CUSTOMER,
# MAGIC     TRANSACTION_DATE DATE,
# MAGIC     TRANSACTION_AMOUNT FLOAT,
# MAGIC     TRANSACTION_TYPE STRING,
# MAGIC     PAYMENT_METHOD STRING
# MAGIC );
# MAGIC